### ISSUE TITLE
UI: Implement UI for Admin to add Donor Details

### ISSUE THREAD

**Issue by Raghunath-Kunigiri** [slu-csci-5030/material-donor-mutual-assist_POC#147]
Acceptance Criteria:
1. Ensure that data fields including First Name, Last Name, Email, and Zip Code are mandatory for donor details.
2. Implement validations, including:
    a. Validation for ensuring the First Name field is not empty.
    b. Validation for ensuring the Email field contains a valid email address format.
    c. Validation for ensuring the Zip Code field follows the correct format for the specified country.
4. Develop unit test cases with at least 85% coverage.

Tasks:
- Task 1: Implement mandatory data entry for First Name, Last Name, Email, and Zip Code fields (1).
- Task 2: Implement validation logic for the First Name field (2).
- Task 3: Write unit test cases to achieve at least 85% coverage (3).

**Comment by Moshrefi** [comment]
@Raghunath9493 Are there any UI sketches or prototypes that we are expected to implement for this task? I want to know if there are any paper drawings or prototypes available to clarify this issue.

**Comment by Moshrefi** [comment]
I found this helpful for it.

![image](https://github.com/slu-csci-5030/material-donor-mutual-assist/assets/62541857/e33355fd-7ef2-48cf-ad44-77945fa49714)
